DEBUG (09/04/2024 13:11:34): server init (Line: 17 [server.py])
DEBUG (09/04/2024 13:11:40): Connection established from ('127.0.0.1', 26682) (Line: 39 [server.py])
DEBUG (09/04/2024 13:11:49): client: 127.0.0.1 - UPLOAD (Line: 179 [commands.py])
DEBUG (09/04/2024 13:12:14): client: 127.0.0.1 - TIME (Line: 179 [commands.py])
DEBUG (09/04/2024 13:12:19): client: 127.0.0.1 - ECHO (Line: 179 [commands.py])
DEBUG (09/04/2024 13:12:35): Connection established from ('127.0.0.1', 26686) (Line: 39 [server.py])
DEBUG (09/04/2024 13:12:37): client: 127.0.0.1 - TIME (Line: 179 [commands.py])
DEBUG (09/04/2024 13:12:41): client: 127.0.0.1 - ECHO (Line: 179 [commands.py])
DEBUG (09/04/2024 13:12:48): client: 127.0.0.1 - ECHO (Line: 179 [commands.py])
DEBUG (09/04/2024 13:12:52): Connection lost with ('127.0.0.1', 26682) (Line: 59 [server.py])
DEBUG (09/04/2024 13:12:58): client: 127.0.0.1 - QUIT (Line: 179 [commands.py])
